### ISSUE TITLE
The name 'home_blueprint' is already registered for this blueprint. Use 'name=' to provide a unique name.

### ISSUE THREAD

**Issue by yuebinge** [SiJiDo/H#28]
运行报错：
Traceback (most recent call last):
  File "run.py", line 33, in <module>
    app = create_app( app_config )
  File "/home/H/H/app/__init__.py", line 41, in create_app
    register_blueprints(app)
  File "/home/H/H/app/__init__.py", line 25, in register_blueprints
    app.register_blueprint(module.blueprint)
  File "/usr/local/lib/python3.8/dist-packages/flask/scaffold.py", line 56, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1028, in register_blueprint
    blueprint.register(self, options)
  File "/usr/local/lib/python3.8/dist-packages/flask/blueprints.py", line 305, in register
    raise ValueError(
ValueError: The name 'home_blueprint' is already registered for this blueprint. Use 'name=' to provide a unique name.

**Comment by Guozhuohang** [comment]
请问你解决了吗

**Comment by Guozhuohang** [comment]
Traceback (most recent call last):
  File "E:\Miniconda\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Miniconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\flasktest\test_env\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "F:\flasktest\test_env\lib\site-packages\flask\cli.py", line 1063, in main
    cli.main()
  File "F:\flasktest\test_env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "F:\flasktest\test_env\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "F:\flasktest\test_env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "F:\flasktest\test_env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "F:\flasktest\test_env\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "F:\flasktest\test_env\lib\site-packages\flask\cli.py", line 354, in decorator
    app = __ctx.ensure_object(ScriptInfo).load_app()
  File "F:\flasktest\test_env\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "F:\flasktest\test_env\lib\site-packages\flask\cli.py", line 235, in locate_app
    return find_best_app(module)
  File "F:\flasktest\test_env\lib\site-packages\flask\cli.py", line 63, in find_best_app
    app = app_factory()
  File "F:\flasktest\RealProject\__init__.py", line 56, in create_app
    app.register_blueprint(blog.bp)
  File "F:\flasktest\test_env\lib\site-packages\flask\scaffold.py", line 51, in wrapper_func
    return f(self, *args, **kwargs)
  File "F:\flasktest\test_env\lib\site-packages\flask\app.py", line 997, in register_blueprint
    blueprint.register(self, options)
  File "F:\flasktest\test_env\lib\site-packages\flask\blueprints.py", line 310, in register
    raise ValueError(
ValueError: The name 'blog' is already registered for this blueprint. Use 'name=' to provide a unique name.

**Comment by Guozhuohang** [comment]
在进入flask shell时报的错
